name: tiktok_smart_cache
description: TikTok Smart Cache App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  dio: ^5.4.0
  video_player: ^2.8.3
  google_mobile_ads: ^5.1.0
  connectivity_plus: ^6.0.3
  flutter_local_notifications: ^17.1.2
  share_plus: ^9.0.0

flutter:
  uses-material-design: true
